#! /bin/sh
### BEGIN INIT INFO
# Provides:          initTrab
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: 
# Description:       
### END INIT INFO

case "$1" in
    start|restart|force-reload)


        # IO 00 gpio11 as input(LFLAG_1) --------------------------------------------------------
        # IO 01 gpio12 as input (DFLAG_1) --------------------------------------------------------
        # IO 02 gpio13 as output (INDEX_1) --------------------------------------------------------
        
        # IO 04 gpio6 as output(EN_1) ------------------------------------------------------------
        # IO 05 gpio0 as input (ELB1) -----------------------------------------------------
        # IO 06 gpio1 as input (ELB2) -----------------------------------------------------
        # IO 07 gpio38 as output (ENABLE) --------------------------------------------------
        # IO 10 gpio10 as output (SS) ------------------------------------------------------
        # IO 11 (MOSI) ---------------------------------------------------------------------
        # IO 12 (MISO) ---------------------------------------------------------------------
        # IO 13 (SCK) ----------------------------------------------------------------------




        # IO 03 pwm1 as output (MOTOR) -----------------------------------------------------
        # Linux: pwm1
        if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
            echo -n "1" > /sys/class/pwm/pwmchip0/export
        fi
        chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
        chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
        chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
        chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
        chmod g+rw /sys/class/pwm/pwmchip0/pwm1/enable
        chmod g+rw /sys/class/pwm/pwmchip0/pwm1/duty_cycle

        # Level Shifter: gpio16 = 0 = out
        if [ ! -d /sys/class/gpio/gpio16 ] ; then
            echo -n "16" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio16/value
        echo -n "out" > /sys/class/gpio/gpio16/direction

        # Resistor: gpio17
        if [ ! -d /sys/class/gpio/gpio17 ] ; then
            echo -n "17" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio17/direction

        # Mux1: gpio76 = 0
        if [ ! -d /sys/class/gpio/gpio76 ] ; then
            echo -n "76" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio76/value

        # Mux2: gpio64 = 1
        if [ ! -d /sys/class/gpio/gpio64 ] ; then
            echo -n "64" > /sys/class/gpio/export
        fi
        echo -n "1" > /sys/class/gpio/gpio64/value




    	;;
    stop)
        echo -n "1" > /sys/class/pwm/pwmchip0/unexport
        echo -n "16" > /sys/class/gpio/unexport
        echo -n "76" > /sys/class/gpio/unexport
        echo -n "64" > /sys/class/gpio/unexport
        ;;
    status)
    	ls -d /sys/class/gpio/gpio*
        ;;
    *)
    	echo -n "Usage: $0 "
    	echo "{start|stop|restart|force-reload|status}"
    	exit 1
    	;;
esac

exit 0